[settings.oci-defaults]

[metadata.settings.oci-defaults]
affected-services = ["oci-defaults"] # TODO: add containerd to this list after testing that template generaiton works!

[services.oci-defaults]
configuration-files = ["oci-defaults"]
restart-commands = []

[configuration-files.oci-defaults]
path = "/etc/containerd/cri-base.json"
template-path = "/usr/share/templates/containerd-cri-base-json"
